linters-settings:
  nlreturn:
    block-size: 2
linters:
  enable:
    - gocritic
    - gofmt
    - gofumpt
    - gomnd
    - govet
    - lll
    - misspell
    - nlreturn
    - stylecheck
    - thelper
    - whitespace
